version: '3.8'

services:
  blazor-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bgbahasajerman-blazor-app
    ports:
      - "8082:80"
    networks:
      - blazor-network
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Use Development for dev/test
    volumes:
      - .:/app                               # ✅ Live sync source into container

networks:
  blazor-network:
    driver: bridge
